# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitlister', '0002_auto_20161013_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='twitid',
            field=models.CharField(max_length=30),
        ),
    ]
