# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitlister', '0004_delete_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitid', models.CharField(max_length=30)),
                ('texto', models.TextField()),
            ],
        ),
    ]
