# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('tags', models.TextField()),
                ('pubdate', models.TextField()),
                ('link', models.TextField()),
                ('thumb', models.TextField()),
                ('author', models.TextField()),
            ],
        ),
    ]
