# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elly',
            name='section',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elly',
            name='views',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
