# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elly', '0002_auto_20161021_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elly',
            name='views',
        ),
    ]
