# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import datetime



def transform_time(apps,schema_editor):
    Elly = apps.get_model('elly','Elly')
    for Elly in Elly.objects.all().iterator():
        date = Elly.pubdate.replace("T", " ")
        try:
            Elly.pubdate2 = datetime.datetime.strptime(date,"%Y-%m-%d %H:%M:%S")
        except ValueError:
            Elly.pubdate2 = datetime.datetime.strptime(date,"%Y-%m-%d %H-%M-%S")
        Elly.save()

class Migration(migrations.Migration):

    dependencies = [
        ('elly', '0005_auto_20161202_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='elly',
            name='pubdate2',
            field=models.DateTimeField(null=True,auto_now=False,auto_now_add=False),
            ),
        migrations.RunPython(transform_time),
        migrations.RenameField(
            model_name='elly',
            old_name='pubdate',
            new_name='pubdate3'
        ),
        migrations.RenameField(
            model_name='elly',
            old_name='pubdate2',
            new_name='pubdate'
        ),
    ]
