# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elly', '0006_auto_20161202_1513'),
    ]

    operations = [
    	migrations.RemoveField(
            model_name='elly',
            name='pubdate3'
            )
    ]
